import { SeasonalPattern } from '@/lib/polygonService';

// Mock data that matches the Seasonax examples for fallback
export const mockSeasonalPatterns: SeasonalPattern[] = [
  {
    symbol: 'URI',
    company: 'United Rentals, Inc',
    sector: 'Industrials',
    marketCap: 'Large-Cap',
    exchange: 'NYSE',
    currency: 'USD',
    startDate: '12 AUG',
    endDate: '18 SEP',
    period: 'Aug 12 - Sep 18',
    annualizedReturn: 159.9,
    averageReturn: 10.16,
    medianReturn: 9.35,
    winningTrades: 14,
    totalTrades: 15,
    winRate: 93.3,
    maxProfit: 32.97,
    maxLoss: -1.34,
    standardDev: 8.61,
    sharpeRatio: 1.18,
    calendarDays: 37,
    years: 21,
    chartData: [
      { period: '13', return: 12.1 },
      { period: '14', return: 8.7 },
      { period: '15', return: -2.3 },
      { period: '16', return: 15.4 },
      { period: '17', return: 9.8 },
      { period: '18', return: 18.2 },
      { period: '19', return: 6.5 },
      { period: '20', return: 11.3 },
      { period: '21', return: 14.7 },
      { period: '22', return: 7.9 }
    ]
  },
  {
    symbol: 'NVDA',
    company: 'NVIDIA Corporation',
    sector: 'Technology',
    marketCap: 'Large-Cap',
    exchange: 'NASDAQ',
    currency: 'USD',
    startDate: '12 AUG',
    endDate: '19 SEP',
    period: 'Aug 12 - Sep 19',
    annualizedReturn: 141.67,
    averageReturn: 9.61,
    medianReturn: 11.35,
    winningTrades: 13,
    totalTrades: 15,
    winRate: 86.7,
    maxProfit: 28.35,
    maxLoss: -7.43,
    standardDev: 8.99,
    sharpeRatio: 1.07,
    calendarDays: 38,
    years: 15,
    chartData: [
      { period: '13', return: 9.2 },
      { period: '14', return: 15.6 },
      { period: '15', return: 11.8 },
      { period: '16', return: -5.1 },
      { period: '17', return: 12.4 },
      { period: '18', return: 8.9 },
      { period: '19', return: 16.3 },
      { period: '20', return: 14.1 },
      { period: '21', return: 10.7 },
      { period: '22', return: 13.5 }
    ]
  },
  {
    symbol: 'PKG',
    company: 'Packaging Corporation of America',
    sector: 'Materials',
    marketCap: 'Large-Cap',
    exchange: 'NYSE',
    currency: 'USD',
    startDate: '12 AUG',
    endDate: '15 SEP',
    period: 'Aug 12 - Sep 15',
    annualizedReturn: 77.4,
    averageReturn: 6.23,
    medianReturn: 7.10,
    winningTrades: 12,
    totalTrades: 15,
    winRate: 80.0,
    maxProfit: 18.45,
    maxLoss: -8.12,
    standardDev: 7.22,
    sharpeRatio: 0.86,
    calendarDays: 34,
    years: 21,
    chartData: [
      { period: '13', return: 7.1 },
      { period: '14', return: 5.8 },
      { period: '15', return: -3.2 },
      { period: '16', return: 9.4 },
      { period: '17', return: 4.6 },
      { period: '18', return: 8.1 },
      { period: '19', return: -6.8 },
      { period: '20', return: 12.3 },
      { period: '21', return: 6.9 },
      { period: '22', return: 8.7 }
    ]
  }
];

// Mock data for NASDAQ 100
export const mockNasdaqPatterns: SeasonalPattern[] = [
  {
    symbol: 'QQQ',
    company: 'Invesco QQQ Trust',
    sector: 'Technology',
    marketCap: 'Large-Cap',
    exchange: 'NASDAQ',
    currency: 'USD',
    startDate: '15 AUG',
    endDate: '20 SEP',
    period: 'Aug 15 - Sep 20',
    annualizedReturn: 125.3,
    averageReturn: 8.9,
    medianReturn: 9.2,
    winningTrades: 12,
    totalTrades: 15,
    winRate: 80.0,
    maxProfit: 24.1,
    maxLoss: -6.8,
    standardDev: 7.9,
    sharpeRatio: 1.13,
    calendarDays: 36,
    years: 15,
    chartData: [
      { period: '13', return: 8.4 },
      { period: '14', return: 11.2 },
      { period: '15', return: 6.8 },
      { period: '16', return: 12.9 },
      { period: '17', return: 7.5 },
      { period: '18', return: 9.8 },
      { period: '19', return: 5.3 },
      { period: '20', return: 13.1 },
      { period: '21', return: 8.7 },
      { period: '22', return: 10.4 }
    ]
  }
];

// Mock data for Dow Jones
export const mockDowPatterns: SeasonalPattern[] = [
  {
    symbol: 'DIA',
    company: 'SPDR Dow Jones Industrial Average ETF',
    sector: 'Industrials',
    marketCap: 'Large-Cap',
    exchange: 'NYSE',
    currency: 'USD',
    startDate: '10 AUG',
    endDate: '25 SEP',
    period: 'Aug 10 - Sep 25',
    annualizedReturn: 98.7,
    averageReturn: 7.2,
    medianReturn: 7.8,
    winningTrades: 11,
    totalTrades: 15,
    winRate: 73.3,
    maxProfit: 19.4,
    maxLoss: -8.9,
    standardDev: 8.2,
    sharpeRatio: 0.88,
    calendarDays: 46,
    years: 15,
    chartData: [
      { period: '13', return: 6.2 },
      { period: '14', return: 9.1 },
      { period: '15', return: 4.5 },
      { period: '16', return: 11.3 },
      { period: '17', return: 5.8 },
      { period: '18', return: 8.7 },
      { period: '19', return: 3.9 },
      { period: '20', return: 12.4 },
      { period: '21', return: 7.1 },
      { period: '22', return: 9.6 }
    ]
  }
];

export const mockFeaturedPatterns: SeasonalPattern[] = [
  {
    symbol: 'AAPL',
    company: 'Apple Inc',
    sector: 'Technology',
    marketCap: 'Large-Cap',
    exchange: 'NASDAQ',
    currency: 'USD',
    startDate: '21 AUG',
    endDate: '16 SEP',
    period: 'Aug 21 - Sep 16',
    annualizedReturn: 95.4,
    averageReturn: 7.2,
    medianReturn: 8.1,
    winningTrades: 11,
    totalTrades: 15,
    winRate: 73.3,
    maxProfit: 22.1,
    maxLoss: -9.4,
    standardDev: 9.8,
    sharpeRatio: 0.73,
    calendarDays: 26,
    years: 15,
    chartData: [
      { period: '13', return: 5.2 },
      { period: '14', return: 8.1 },
      { period: '15', return: -4.3 },
      { period: '16', return: 11.2 },
      { period: '17', return: 6.8 },
      { period: '18', return: 9.5 },
      { period: '19', return: -7.1 },
      { period: '20', return: 13.4 },
      { period: '21', return: 4.9 },
      { period: '22', return: 7.6 }
    ]
  },
  {
    symbol: 'MSFT',
    company: 'Microsoft Corporation',
    sector: 'Technology',
    marketCap: 'Large-Cap',
    exchange: 'NASDAQ',
    currency: 'USD',
    startDate: '20 AUG',
    endDate: '19 SEP',
    period: 'Aug 20 - Sep 19',
    annualizedReturn: 112.8,
    averageReturn: 8.9,
    medianReturn: 9.2,
    winningTrades: 13,
    totalTrades: 15,
    winRate: 86.7,
    maxProfit: 19.8,
    maxLoss: -6.2,
    standardDev: 7.4,
    sharpeRatio: 1.2,
    calendarDays: 30,
    years: 15,
    chartData: [
      { period: '13', return: 8.3 },
      { period: '14', return: 6.7 },
      { period: '15', return: 12.1 },
      { period: '16', return: 4.5 },
      { period: '17', return: 9.8 },
      { period: '18', return: 7.2 },
      { period: '19', return: 11.6 },
      { period: '20', return: -4.1 },
      { period: '21', return: 10.3 },
      { period: '22', return: 8.9 }
    ]
  },
  {
    symbol: 'GOOGL',
    company: 'Alphabet Inc',
    sector: 'Technology',
    marketCap: 'Large-Cap',
    exchange: 'NASDAQ',
    currency: 'USD',
    startDate: '20 AUG',
    endDate: '14 SEP',
    period: 'Aug 20 - Sep 14',
    annualizedReturn: 89.2,
    averageReturn: 6.1,
    medianReturn: 6.8,
    winningTrades: 10,
    totalTrades: 15,
    winRate: 66.7,
    maxProfit: 16.3,
    maxLoss: -11.2,
    standardDev: 8.9,
    sharpeRatio: 0.69,
    calendarDays: 25,
    years: 15,
    chartData: [
      { period: '13', return: 4.1 },
      { period: '14', return: 9.2 },
      { period: '15', return: -8.3 },
      { period: '16', return: 7.6 },
      { period: '17', return: 5.4 },
      { period: '18', return: 11.8 },
      { period: '19', return: -5.7 },
      { period: '20', return: 8.9 },
      { period: '21', return: 6.2 },
      { period: '22', return: 9.4 }
    ]
  }
];
