// QUALITY UNIVERSE — filtered from TOP_1800_SYMBOLS: market cap >= $25B AND price >= $30
// Generated 2026-09-08 via scripts/test-marketcap-filter.mjs from scripts/marketcap-filter-results.json
// Re-run scripts/test-marketcap-filter.mjs to refresh (excludes ETFs/ETNs and no-data tickers).

export const QUALITY_SYMBOLS = [
    'NVDA', 'AAPL', 'GOOGL', 'GOOG', 'MSFT', 'AMZN', 'TSM', 'SPCX', 'AVGO', 'META',
    'TSLA', 'SKHY', 'MU', 'BRK.A', 'BRK.B', 'LLY', 'JPM', 'WMT', 'AMD', 'V',
    'JNJ', 'ASML', 'XOM', 'MA', 'INTC', 'ORCL', 'ABBV', 'BAC', 'CSCO', 'PLTR',
    'CVX', 'COST', 'LRCX', 'KO', 'CAT', 'MRK', 'HSBC', 'AMAT', 'UNH', 'GE',
    'MS', 'PG', 'DELL', 'NFLX', 'HD', 'NVS', 'GS', 'RY', 'PM', 'BABA',
    'WFC', 'PANW', 'RTX', 'ARM', 'SHEL', 'SNDK', 'AZN', 'GEV', 'SAP', 'ANET',
    'KLAC', 'AMGN', 'TXN', 'TM', 'C', 'BHP', 'TMO', 'IBM', 'AXP', 'LIN',
    'CRWD', 'CRM', 'VZ', 'NVO', 'APH', 'MRVL', 'TD', 'TTE', 'TMUS', 'STX',
    'SCHW', 'PEP', 'ABT', 'GILD', 'DE', 'SHOP', 'DIS', 'MCD', 'QCOM', 'ADI',
    'NEE', 'BLK', 'UNP', 'WELL', 'UBS', 'WDC', 'RIO', 'SCCO', 'BA', 'COP',
    'ETN', 'BUD', 'UBER', 'NOW', 'DHR', 'TJX', 'BKNG', 'VRTX', 'UL', 'BMY',
    'NEM', 'COF', 'GLW', 'CB', 'SPGI', 'PLD', 'ISRG', 'PGR', 'CVS', 'BMO',
    'PH', 'LMT', 'MDT', 'BTI', 'SBUX', 'PDD', 'SNOW', 'SYK', 'MO', 'LOW',
    'FTNT', 'ACN', 'BNS', 'BP', 'BNY', 'SPOT', 'ADP', 'HOOD', 'ENB', 'MPC',
    'IBN', 'VRT', 'APP', 'ABNB', 'VLO', 'CM', 'ING', 'SNY', 'ADBE', 'CEG',
    'MCK', 'FCX', 'CNQ', 'AEM', 'HWM', 'EQIX', 'BX', 'PSX', 'SO', 'CME',
    'MELI', 'GSK', 'EQNR', 'NET', 'USB', 'TT', 'PNC', 'ASX', 'GD', 'KKR',
    'PWR', 'DUK', 'DASH', 'CSX', 'INTU', 'WMB', 'ICE', 'BN', 'MRSH', 'ELV',
    'JCI', 'MAR', 'HCA', 'WM', 'UPS', 'MMM', 'MNST', 'MCO', 'SLB', 'EMR',
    'REGN', 'EPD', 'AMT', 'SHW', 'BAM', 'CDNS', 'CP', 'CTAS', 'LITE', 'APO',
    'SU', 'NGG', 'ECL', 'MDLZ', 'DB', 'MSI', 'CMI', 'TRV', 'GM', 'ITW',
    'DDOG', 'NTES', 'FDX', 'EOG', 'SNPS', 'TGT', 'CI', 'CNI', 'BE', 'NSC',
    'ROST', 'B', 'MFC', 'NOC', 'RACE', 'ORLY', 'RCL', 'CL', 'WPM', 'HLT',
    'KMI', 'DLR', 'BSX', 'HPE', 'SE', 'AON', 'RSG', 'AEP', 'SPG', 'AJG',
    'APD', 'HON', 'PCAR', 'ALL', 'TRP', 'ARGX', 'TDG', 'COR', 'TFC', 'BKR',
    'URI', 'CRH', 'GWW', 'TRGP', 'MET', 'RELX', 'NBIS', 'MPLX', 'TEL', 'LNG',
    'OKE', 'MPWR', 'OXY', 'CVE', 'MT', 'NUE', 'AFL', 'CTVA', 'MRNA', 'O',
    'D', 'CAH', 'NXPI', 'NKE', 'FAST', 'MSTR', 'FIX', 'TER', 'FANG', 'KEYS',
    'PSA', 'COHR', 'AU', 'SRE', 'AME', 'NDAQ', 'ALAB', 'CVNA', 'GRMN', 'STT',
    'DVN', 'DAL', 'EW', 'FNV', 'ETR', 'HONA', 'BDX', 'VST', 'CBRS', 'FITB',
    'XYZ', 'DEO', 'AMP', 'CRWV', 'CARR', 'COIN', 'AZO', 'HUM', 'ROK', 'TEAM',
    'WAB', 'LHX', 'NTRA', 'XEL', 'WDAY', 'PYPL', 'CMG', 'CCEP', 'STM', 'VTR',
    'EBAY', 'TRI', 'ADSK', 'CIEN', 'HEI', 'RVMD', 'EXC', 'VEEV', 'KDP', 'FERG',
    'IQV', 'CCJ', 'PAYX', 'CBRE', 'A', 'TEVA', 'GFI', 'IDXX', 'PRU', 'IBKR',
    'AXON', 'FER', 'MSCI', 'WCN', 'YUM', 'RKLB', 'FMX', 'ADM', 'ONC', 'FLEX',
    'LYV', 'ROP', 'MCHP', 'WAT', 'TTWO', 'DHI', 'AIG', 'ED', 'CLS', 'ODFL',
    'SYY', 'VIK', 'NTR', 'EL', 'HIG', 'PEG', 'KGC', 'MLM', 'NTAP', 'UAL',
    'KR', 'TWLO', 'EXPE', 'ALNY', 'KMB', 'HSY', 'IRM', 'STLD', 'MTB', 'WEC',
    'EQT', 'RJF', 'NTRS', 'ALC', 'VMC', 'TECK', 'BIDU', 'ACGL', 'EME', 'DXCM',
    'CNC', 'P', 'ILMN', 'RMD', 'BIIB', 'JBL', 'CCI', 'MDLN', 'CRDO', 'ARES',
    'ZTS', 'FTI', 'CPRT', 'CBOE', 'GEHC', 'WTW', 'RBLX', 'HAL', 'BAP', 'OKTA',
    'CFG', 'RDDT', 'MDB', 'IR', 'ZM', 'AEE', 'HPQ', 'EXR', 'DG', 'ON',
    'LVS', 'RYAAY', 'ATI', 'TS', 'RPRX', 'DTE', 'ATO', 'TDY', 'LPLA', 'FTS',
    'FISV', 'PBA', 'SUNB', 'CTSH', 'CASY', 'AWK', 'QSR', 'ZS', 'INSM', 'FOXA',
    'CPAY', 'OTIS', 'FE', 'MTD', 'WSM', 'ES', 'LH', 'PPL', 'VRSN', 'CINF',
    'DGX', 'CNP', 'ECHO', 'BNTX', 'SMCI', 'SYF', 'DOV', 'RF', 'CRCL', 'TCOM',
    'JBHT', 'INCY', 'WRB', 'NVT', 'ROIV', 'Q', 'TSEM', 'NRG', 'PPG',
]
